TOPDIR ?= ../../..
include $(TOPDIR)/.config

$(BADGE_SUPPORT)_SRC += hardware/input/badge/interrupt.c
$(INOUT_TRISO_SUPPORT)_SRC += hardware/input/badge/triso.c
$(KDE_KDR1000_SUPPORT)_SRC += hardware/input/badge/kdr1000.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
