TOPDIR ?= ../..

$(EXTERNAL_WATCHDOG_SUPPORT)_SRC += hardware/watchdog/external-watchdog.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
