TOPDIR ?= ../..
include $(TOPDIR)/.config

$(MAE16360IP_SUPPORT)_SRC += services/mae16360ip/mae16360ip.c
# $(MAE16360IP_SUPPORT)_ECMD_SRC += services/mae16360ip/ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
