TOPDIR ?= ../../..
include $(TOPDIR)/.config

$(INOUT_TRISO_SUPPORT)_SRC += hardware/rfid/inout/triso.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
