TOPDIR ?= ../..
include $(TOPDIR)/.config

$(MAE16360IP_SUPPORT)_SRC += protocols/mae16360ip/fobos.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
