TOPDIR ?= ../../..
include $(TOPDIR)/.config

$(MATRIX_BUTTONS_INPUT_SUPPORT)_SRC += hardware/input/matrixbuttons/matrixbuttons.c
$(MATRIX_BUTTONS_INPUT_SUPPORT)_ECMD_SRC += hardware/input/matrixbuttons/matrixbuttons_ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
